### ISSUE TITLE
connection recovery failed, when one server goes down

### ISSUE THREAD

**Issue by suraj16thjan** [socketio/socket.io-redis-streams-adapter#27]
Senario: I have multi node server setup. Suppose a client is connected to server 1,  and whenever the server 1 goes down, i dont get connection recovery on other server.

```
const io = new Server(fastify.server, {
    cors: {
      origin: JSON.parse(config.SOCKET_CORS_ORIGIN),
      credentials: true,
    },
    connectionStateRecovery: {
      // the backup duration of the sessions and the packets
      maxDisconnectionDuration: 2 * 60 * 1000,
      // whether to skip middlewares upon successful recovery
      skipMiddlewares: true,
    },
    adapter: createAdapter(redisClient, {}),
  });
```
It only recovers when the transport is closed from client side.

**Comment by Sufo10** [comment]
I am also facing the same issue in a Kubernetes cluster. I have 2 different nodes with 2 different servers. The underlying adapter is redis streams adapter. When one nodes goes down, the connection state is not recovered in another server. However, a new connection with new connection id is created.

**Comment by aishwaryawambule** [comment]
Since the connection is dependent on the TCP ports, each socket connection is established on these ports. Each socket connection is dependent and connected to the port of each pod.  So, if the connection is recovered or reconnected to the same pod/server where the previous connection was established, the connection might be recovered. But if after the disconnection if the port of different server/pod is connected though it be the same port number,  it cannot be recovered. I have been facing this issue too and I am looking for the solution. If anyone has found the solution please help.

**Comment by darrachequesne** [comment]
Hi! The connection state is persisted upon client disconnection, which means the server must be gracefully closed for it to work:

```js
process.on("SIGTERM", () => {
  io.close();
});
```

That being said, please be aware that connection state recovery is attempted in a best effort basis, and you shouldn't depend on it in your application.

**Comment by suraj16thjan** [comment]
thanks it worked @darrachequesne

**Comment by suraj16thjan** [comment]
@darrachequesne  thanks to you
